local tileString = [[
WWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WGGGGGGGGGGGGGGGGGGGFGGGFFGFW
WGGGGGGGGGGGGGGGGGGGFGFGFFGFW
WGGGGGGGGGGGGGGGGGGGGGGGFFGFW
WFGGGGGGGGGGGGGGGGGGGGGGGGGFW
WFGGGGGGGGGGGGGGGFFFGGGGGGGFW
WFGGGGGGGGGGGGGGGFFFGGGGGGGFW
WFGGGGGGGGGGGGGGGFFFGGGGGGGFW
WFGGGGGGGGGGGGGGGRRRGGGGGGGFW
WFGGGGGGGGGGGGGGGGGGGGGGFFGFW
WFGGGGGGGGGGGGGGGGGGGGGGFFGFW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWW
]]

local frameSize = 32
local quadInfo = { 
  { 'G',  0,  0 }, --  grass
  { 'F',  0,  32 }, -- flowers
  { 'W', 32,  32 }, -- wood
  { 'R', 32,   0 }  -- other wall 
}

newMap(32,32,'/images/countryside.png', tileString, quadInfo)
